# Use an official Python image as the base
FROM python:3.12-slim

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file
COPY requirements.in .

# Install the dependencies
RUN pip install --no-cache-dir pip-tools
RUN pip-compile requirements.in --resolver=backtracking
RUN pip-sync requirements.txt

# Copy the application code
COPY . .

# Expose the port
EXPOSE 8000

# Run the command to start the development server
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]